/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gid;

import BLL.Filmi;
import BLL.Perdoruesi;
import DAL.BiletaRepository;
import DAL.FilmiException;
import DAL.FilmiRepository;
import DAL.PerdoruesiException;
import DAL.PerdoruesiRepository;
import DAL.SallaRepository;
import DAL.StreamingFilmatRepository;
import DialogFrames.DeactivatedErorr;
import DialogFrames.YouAreDenied;
import ForCostumers.MovieSliderFrame;
import GUIInternalFrame.PerdoruesiFormReal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Dren
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    static Perdoruesi usernamePerdorues = null;
    static int countErorr = 0;
    
    PerdoruesiRepository perdoruesiRepository = new PerdoruesiRepository();
    SallaRepository sallatRepository = new SallaRepository();
    StreamingFilmatRepository streamingFilmatRepository = new StreamingFilmatRepository();
    FilmiRepository filmiRepository = new FilmiRepository();
    SallaRepository sallaRepository = new SallaRepository();
    BiletaRepository biletaRepository = new BiletaRepository();
    
    
    public Dashboard() {
        initComponents();
        loadPerdoruesPanel();
        loadMoviesPanel();
        loadTicketsPanel();
        loadHallsPanel();
        loadch();
        loadPanelTwo();
        
    }

    public Dashboard(Perdoruesi username) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        usernamePerdorues = username;
        loadPerdoruesPanel();
        loadMoviesPanel();
        loadTicketsPanel();
        loadHallsPanel();
        if(username.getRoliID().getRoliID() == 2){
            jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconForInternalFrame/puntoriIconDashboard.png"))); // NOI18N
        }
        jLabel9.setText(username.getUsername().toUpperCase());
        updateClock();
       clickedPuntorOrAdmin();
       loadch();
       loadPanelTwo();
        
        
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        booktpanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        moviesliderp = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        addmoviepanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalUsers1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalMovies = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totalHalls = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        totalTickets = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        panelforChart1 = new javax.swing.JPanel();
        panelforChart2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(22, 96, 131));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        booktpanel.setBackground(new java.awt.Color(22, 96, 131));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_ticket_24px.png"))); // NOI18N
        jLabel12.setText("Book a Ticket");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel12MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });

        javax.swing.GroupLayout booktpanelLayout = new javax.swing.GroupLayout(booktpanel);
        booktpanel.setLayout(booktpanelLayout);
        booktpanelLayout.setHorizontalGroup(
            booktpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(booktpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        booktpanelLayout.setVerticalGroup(
            booktpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.add(booktpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 150, 50));

        moviesliderp.setBackground(new java.awt.Color(22, 96, 131));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_slider_control_24px_1.png"))); // NOI18N
        jLabel10.setText("Movie Slider");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });

        javax.swing.GroupLayout moviesliderpLayout = new javax.swing.GroupLayout(moviesliderp);
        moviesliderp.setLayout(moviesliderpLayout);
        moviesliderpLayout.setHorizontalGroup(
            moviesliderpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviesliderpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        moviesliderpLayout.setVerticalGroup(
            moviesliderpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.add(moviesliderp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 150, 50));

        addmoviepanel.setBackground(new java.awt.Color(22, 96, 131));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_insert_table_24px.png")); // NOI18N
        jLabel13.setText("Add a Movie");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });

        javax.swing.GroupLayout addmoviepanelLayout = new javax.swing.GroupLayout(addmoviepanel);
        addmoviepanel.setLayout(addmoviepanelLayout);
        addmoviepanelLayout.setHorizontalGroup(
            addmoviepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addmoviepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        addmoviepanelLayout.setVerticalGroup(
            addmoviepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.add(addmoviepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 50));

        jPanel1.setBackground(new java.awt.Color(22, 96, 131));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_streaming_24px_1.png"))); // NOI18N
        jLabel14.setText("Streaming");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        jPanel11.setBackground(new java.awt.Color(22, 96, 131));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_movie_24px.png")); // NOI18N
        jLabel15.setText("Show Movies");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(25, 25, 25))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 150, 50));

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Filmix");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 80, 70));

        jPanel12.setBackground(new java.awt.Color(12, 86, 121));
        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_database_26px_2.png"))); // NOI18N
        jLabel21.setText("Database");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel21)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 150, 50));

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_sign_out_16px.png")); // NOI18N
        jLabel20.setText("Sign out");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 700));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconForInternalFrame/adminIcon.png"))); // NOI18N
        jLabel9.setText("emri jem");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(22, 96, 131));
        jLabel11.setText("12:00:00");

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_settings_24px_2.png")); // NOI18N
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(22, 96, 131));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(22, 96, 131));
        jLabel18.setText("Search:");

        jTextField1.setBackground(new java.awt.Color(210, 210, 210));
        jTextField1.setForeground(new java.awt.Color(22, 96, 131));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_search_24px_6.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(22, 22, 22))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1)
                        .addComponent(jLabel18)
                        .addComponent(jLabel11)))
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 980, 50));

        jPanel6.setBackground(new java.awt.Color(47, 47, 43));

        jPanel7.setBackground(new java.awt.Color(31, 179, 243));
        jPanel7.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_staff_50px.png")); // NOI18N
        jPanel7.add(jLabel3);
        jLabel3.setBounds(10, 40, 95, 40);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Users");
        jPanel7.add(jLabel4);
        jLabel4.setBounds(10, 10, 120, 16);

        totalUsers1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        totalUsers1.setForeground(new java.awt.Color(255, 255, 255));
        totalUsers1.setText("10");
        jPanel7.add(totalUsers1);
        totalUsers1.setBounds(90, 30, 54, 50);

        jPanel8.setBackground(new java.awt.Color(215, 118, 254));
        jPanel8.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Movies");
        jPanel8.add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_movies_folder_50px.png")); // NOI18N
        jPanel8.add(jLabel6);
        jLabel6.setBounds(10, 40, 95, 40);

        totalMovies.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        totalMovies.setForeground(new java.awt.Color(255, 255, 255));
        totalMovies.setText("100");
        jPanel8.add(totalMovies);
        totalMovies.setBounds(80, 30, 90, 50);

        jPanel9.setBackground(new java.awt.Color(250, 174, 88));
        jPanel9.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total Halls");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(10, 10, 86, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_curtains_60px.png")); // NOI18N
        jPanel9.add(jLabel8);
        jLabel8.setBounds(10, 40, 95, 40);

        totalHalls.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        totalHalls.setForeground(new java.awt.Color(255, 255, 255));
        totalHalls.setText("10");
        jPanel9.add(totalHalls);
        totalHalls.setBounds(90, 30, 54, 50);

        jPanel10.setBackground(new java.awt.Color(111, 221, 114));
        jPanel10.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Total Tickets");
        jPanel10.add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_two_tickets_50px.png")); // NOI18N
        jPanel10.add(jLabel1);
        jLabel1.setBounds(10, 40, 95, 40);

        totalTickets.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        totalTickets.setForeground(new java.awt.Color(255, 255, 255));
        totalTickets.setText("100");
        jPanel10.add(totalTickets);
        totalTickets.setBounds(80, 30, 90, 50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelforChart1.setBackground(new java.awt.Color(255, 255, 255));
        panelforChart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelforChart1.setLayout(new java.awt.BorderLayout());

        panelforChart2.setBackground(new java.awt.Color(255, 255, 255));
        panelforChart2.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(484, 484, 484)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(panelforChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelforChart2, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelforChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelforChart2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 980, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       for(double i = 0.0; i<1.0;i=i+ 0.1){
          String value = i+ "";
          float f = Float.valueOf(value);
          this.setOpacity(f);
          try{
              Thread.sleep(50);
          }catch(Exception e){
              e.printStackTrace();
          }
      }
        
    }//GEN-LAST:event_formWindowOpened
        static int xx,yy;
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      xx = evt.getX();
      yy = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x-xx, y-yy);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel12MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseEntered
        setHoverColor(booktpanel);
    }//GEN-LAST:event_jLabel12MouseEntered

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        setExitedColor(booktpanel);
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        setHoverColor(moviesliderp);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        setExitedColor(moviesliderp);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        setHoverColor(addmoviepanel);
    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        setExitedColor(addmoviepanel);
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        setHoverColor(jPanel1);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        setExitedColor(jPanel1);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
         
        MovieSliderFrame m = new MovieSliderFrame();
       m.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        this.dispose();
        AddAMovieForm a = new AddAMovieForm();
        a.setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.dispose();
        StreamingForm s = new StreamingForm();
        s.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.dispose();
        AddTicketForm a = new AddTicketForm();
        a.setVisible(true);
        
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        setHoverColor(jPanel11);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        setExitedColor(jPanel11);
    }//GEN-LAST:event_jLabel15MouseExited

//    public void setFlagPanelVisible(){
//        flagPanel.setVisible(false);
//    }
    
    static boolean buttonFlag = false;
    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
//        if(!buttonFlag){
//            flagPanel.setVisible(true);
//            buttonFlag = true;
//        }else{
//            flagPanel.setVisible(false);
//            System.out.println();
//            buttonFlag = false;
//        }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        TableStreamingShow d = new TableStreamingShow();
        d.setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked

        //null
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
     //  jLabelMouseClickedAdmin(evt);
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        this.dispose();
        Home h = new Home();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
            
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
       if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
                
                String choice = jTextField1.getText();
                System.out.println("d");
                switch(choice){
                    case "Book a Ticket":
                        this.dispose();
                        AddTicketForm a = new AddTicketForm();
                        a.setVisible(true);
                        break;
                    case "Movie Slider":
                        this.dispose();
                        MovieSliderFrame m = new MovieSliderFrame();
                        m.setVisible(true);
                        break;
                    case "Show Movies":
                        this.dispose();
                        TableStreamingShow s = new TableStreamingShow();
                        s.setVisible(true);
                        break;
                    case "Add a Movie":
                        this.dispose();
                        AddAMovieForm aa = new AddAMovieForm();
                        aa.setVisible(true);
                        break;
                    case "Database":
                        this.dispose();
                        DashboardDatabase d = new DashboardDatabase();
                        d.setVisible(true);
                        break;
                    default:
                        JOptionPane.showMessageDialog(this,"Nuk gjendet ne listen tone");
                } 
                
            }
    }//GEN-LAST:event_jTextField1KeyReleased

    
    private void jLabelMouseClickedAdmin(java.awt.event.MouseEvent evt){
        DashboardDatabase d = new DashboardDatabase();
        this.dispose();
        d.setVisible(true);
    }
    
    private void jLabelMouseClickedPuntor(java.awt.event.MouseEvent evt){
        countErorr++;
        if(countErorr < 3){
        YouAreDenied denied = new YouAreDenied(this, true);
        denied.setVisible(true);
        }else{
            try {
                //largoje prej logi-init dhe dergoja nje mesazh
               // JOptionPane.showMessageDialog(this, "Llogaria juaj eshte deaktivizuar , mos e perserit gabimin :)");
                DeactivatedErorr deactivatedErorr = new DeactivatedErorr(this, true);
                deactivatedErorr.setVisible(true);
                Perdoruesi p = perdoruesiRepository.findbyUsername(usernamePerdorues.getUsername());
                perdoruesiRepository.remove(p);
                this.dispose();
                Home h = new Home();
                h.setVisible(true);
            } catch (PerdoruesiException ex) {
                Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    
    }
    //event do te caktoj qe puntori mos ta hap dritatren e databases. 
    
    public void clickedPuntorOrAdmin(){
     jLabel21.addMouseListener(new MouseAdapter(){
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if(usernamePerdorues.getRoliID().getRoliID() == 1){
                jLabelMouseClickedAdmin(evt);
                
            }else{
                    jLabelMouseClickedPuntor(evt);
                }
                
        }
    });
    }
    
    public void loadPanelTwo(){
        try {
            DefaultCategoryDataset categoryDataset = new DefaultCategoryDataset();
            ArrayList<String> lista = sallaRepository.treMusketieret();
            String emriPare = lista.get(0);
            int emriPareNumri = Integer.parseInt(lista.get(1));
            String emriDyte = lista.get(2);
            int emriDyteNumri = Integer.parseInt(lista.get(3));
            String emriTret = lista.get(4);
            int emriTretNumri = Integer.parseInt(lista.get(5));
            categoryDataset.setValue(emriPareNumri,"d",emriPare);
            categoryDataset.setValue(emriDyteNumri,"D",emriDyte);
            categoryDataset.setValue(emriTretNumri,"d",emriTret);
            JFreeChart chart = ChartFactory.createBarChart3D("Top 3 Sallat","Sallat","Kapaciteti", categoryDataset,PlotOrientation.VERTICAL,false,true,false);
            CategoryPlot p = chart.getCategoryPlot();
            p.setRangeGridlinePaint(Color.BLACK);
            
            ChartPanel chartPanel = new ChartPanel(chart);
              panelforChart2.add(chartPanel,BorderLayout.CENTER);
            chartPanel.setVisible(true);
            panelforChart2.validate();
        } catch (PerdoruesiException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    }                      
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    public void loadPerdoruesPanel(){
        int count = perdoruesiRepository.findAll().size();
         totalUsers1.setText(String.valueOf(count));
    }
    public void loadMoviesPanel(){
        int count = filmiRepository.findAll().size();
        totalMovies.setText(String.valueOf(count));
    }
    public void loadHallsPanel(){
        try {
            int count = sallaRepository.findAll().size();
            totalHalls.setText(String.valueOf(count));
        } catch (FilmiException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void loadTicketsPanel(){
        int count = biletaRepository.findAll().size();
        totalTickets.setText(String.valueOf(count));
    }
    
    public static Perdoruesi getPerdoruesUsername(){
        return usernamePerdorues;
    }
    //side panels
    public void setHoverColor(JPanel jpanel){
        jpanel.setBackground(new Color(12,86,121));
    }
    public void setExitedColor(JPanel jpanel){
        jpanel.setBackground(new Color(22,96,131));
    }
    
    
    
    public void loadch(){
        try {
            String resultForChartOne [] = streamingFilmatRepository.repeatedFilmMax(); // max;
            String resultForChartOneFilmiMin []= streamingFilmatRepository.repeatedFilmMin(); //min
            
            
            Integer emriFilmitMax = Integer.parseInt(resultForChartOne[0]);
            Integer emriFilmitMin = Integer.parseInt(resultForChartOneFilmiMin[0]);
            
            Filmi f = filmiRepository.findByID(emriFilmitMax);
            Filmi fmin = filmiRepository.findByID(emriFilmitMin);
            
            Integer numriFilmitMax = Integer.parseInt(resultForChartOne[1]);
            Integer numriFilmitMin = Integer.parseInt(resultForChartOneFilmiMin[1]);
            
            DefaultPieDataset pieDataset = new DefaultPieDataset();
            
            
            pieDataset.setValue(f.getEmriFilmit(),numriFilmitMax);
            pieDataset.setValue(fmin.getEmriFilmit(), numriFilmitMin);
            
            JFreeChart chart = ChartFactory.createPieChart3D(null, pieDataset);
           
            PiePlot p= (PiePlot)chart.getPlot();
            
            // p.setForegroundAlpha(TOP_ALIGNMENT);
            ChartPanel chartPanel = new ChartPanel(chart);
            chart.getPlot().setBackgroundPaint(new Color(255,255,255));
           
            panelforChart1.removeAll();
            panelforChart1.add(chartPanel,BorderLayout.CENTER);
            chartPanel.setVisible(true);
            panelforChart1.validate();
        } catch (FilmiException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
  
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addmoviepanel;
    private javax.swing.JPanel booktpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel moviesliderp;
    private javax.swing.JPanel panelforChart1;
    private javax.swing.JPanel panelforChart2;
    private javax.swing.JLabel totalHalls;
    private javax.swing.JLabel totalMovies;
    private javax.swing.JLabel totalTickets;
    private javax.swing.JLabel totalUsers1;
    // End of variables declaration//GEN-END:variables
 
    
    public void updateClock(){
        Thread clock = new Thread(new Runnable() {

            @Override
            public void run() {
               try{
                   for(;;){
                       Calendar calendar = new GregorianCalendar();
                       
                       int sekondi = calendar.get(Calendar.SECOND);
                       int minuta = calendar.get(Calendar.MINUTE);
                       int hour = calendar.get(Calendar.HOUR);
                       
                       jLabel11.setText(hour + ":" + minuta +":" + sekondi);
                       
                       
                       Thread.sleep(1000);
                       
               }
            }catch(InterruptedException e){
                e.printStackTrace();
            }
        }
           
    });
        clock.start();
        
    

    }
}
    
