/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gid;

import UtilityEffects.FrameShakingEffect;
import BLL.Perdoruesi;
import BLL.Roli;
import DAL.FilmiException;
import DAL.PerdoruesiException;
import DAL.PerdoruesiRepository;
import DialogFrames.AuthentitacionError;
import DialogFrames.EasterEggFrame;
import DialogFrames.PerdoruesiNotFound;
import GUI.HelpFrame;
import GUI.ResetPasswordPanel;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Dren
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    PerdoruesiRepository pr = new PerdoruesiRepository();
    
    public Home() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is alwaysav
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        popCornGif = new javax.swing.JLabel();
        logoIcon = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        nameFilmix = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        usernameText = new javax.swing.JLabel();
        paswordbre = new javax.swing.JPasswordField();
        passwordText = new javax.swing.JLabel();
        SignUpButton = new javax.swing.JLabel();
        SignInButton = new javax.swing.JLabel();
        notHiddenIcon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setOpacity(0.0F);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        loginPanel.setBackground(new java.awt.Color(47, 47, 43));
        loginPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginPanelMouseClicked(evt);
            }
        });
        loginPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                loginPanelKeyTyped(evt);
            }
        });

        popCornGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gid/cinema.gif"))); // NOI18N
        popCornGif.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                popCornGifMouseDragged(evt);
            }
        });
        popCornGif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                popCornGifMouseClicked(evt);
            }
        });

        logoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_3d_glasses_60px_4.png"))); // NOI18N
        logoIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoIconMouseClicked(evt);
            }
        });

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_cancel_24px_3.png"))); // NOI18N
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        nameFilmix.setFont(new java.awt.Font("Century Gothic", 1, 26)); // NOI18N
        nameFilmix.setForeground(new java.awt.Color(255, 255, 255));
        nameFilmix.setText("FILMIX");
        nameFilmix.setToolTipText("");
        nameFilmix.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        emailTextField.setBackground(new java.awt.Color(47, 47, 43));
        emailTextField.setColumns(2);
        emailTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTextField.setForeground(new java.awt.Color(255, 255, 255));
        emailTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        emailTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailTextFieldMouseClicked(evt);
            }
        });
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        usernameText.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        usernameText.setForeground(new java.awt.Color(255, 255, 255));
        usernameText.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_username_16px_1.png")); // NOI18N
        usernameText.setText("Username");

        paswordbre.setBackground(new java.awt.Color(47, 47, 43));
        paswordbre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paswordbre.setForeground(new java.awt.Color(214, 75, 75));
        paswordbre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        paswordbre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paswordbreActionPerformed(evt);
            }
        });
        paswordbre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paswordbreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                paswordbreKeyTyped(evt);
            }
        });

        passwordText.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        passwordText.setForeground(new java.awt.Color(255, 255, 255));
        passwordText.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_keepass_16px.png")); // NOI18N
        passwordText.setText("Password");

        SignUpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gid/2XSignUpButton.png"))); // NOI18N
        SignUpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignUpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpButtonMouseClicked(evt);
            }
        });

        SignInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gid/SigninShadowButton.png"))); // NOI18N
        SignInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SignInButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignInButtonMouseClicked(evt);
            }
        });

        notHiddenIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gid/passwordSeen.png"))); // NOI18N
        notHiddenIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notHiddenIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notHiddenIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notHiddenIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notHiddenIconMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/helpicon_1.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(214, 75, 75));
        jLabel1.setText("Forgot password");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_moon_symbol_30px_4.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\AppData\\Local\\Temp\\icons8_minimize_window_25px.png")); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(popCornGif)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exitButton))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(SignInButton)
                                .addGap(46, 46, 46)
                                .addComponent(SignUpButton)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(loginPanelLayout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(logoIcon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(usernameText)
                                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(passwordText)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                            .addComponent(paswordbre))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(notHiddenIcon))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginPanelLayout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(nameFilmix)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(popCornGif)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(logoIcon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameFilmix)
                        .addGap(45, 45, 45)
                        .addComponent(usernameText)
                        .addGap(18, 18, 18)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(passwordText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paswordbre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(notHiddenIcon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignInButton)
                            .addComponent(SignUpButton))
                        .addGap(43, 43, 43))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exitButton)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
    
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void loginPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginPanelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_loginPanelMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
      xx = evt.getX();
      yy = evt.getY();
    }//GEN-LAST:event_formMouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       
        setLocation(x-xx,y-yy);
    }//GEN-LAST:event_formMouseDragged

    private void popCornGifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popCornGifMouseClicked
        xx = evt.getX();
      yy = evt.getY();
    }//GEN-LAST:event_popCornGifMouseClicked

    private void popCornGifMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popCornGifMouseDragged
        
        int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       
        setLocation(x-xx,y-yy);
    }//GEN-LAST:event_popCornGifMouseDragged

    private void notHiddenIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notHiddenIconMouseEntered
     paswordbre.setEchoChar((char)0);
     
    }//GEN-LAST:event_notHiddenIconMouseEntered

    private void notHiddenIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notHiddenIconMouseClicked
       // jPasswordField1.setEchoChar((char)0);
    }//GEN-LAST:event_notHiddenIconMouseClicked

    private void notHiddenIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notHiddenIconMouseExited
        paswordbre.setEchoChar('*');
    }//GEN-LAST:event_notHiddenIconMouseExited

    private void paswordbreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paswordbreKeyTyped
    
        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gid/pandaicon.png")));
        
    }//GEN-LAST:event_paswordbreKeyTyped

    private void SignInButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignInButtonMouseClicked
       if(emailTextField.getText().length() == 0 || paswordbre.getText().length() == 0){
           FrameShakingEffect.vibrate(this);
          AuthentitacionError a = new AuthentitacionError(this, true);
           a.setVisible(true);
            
       }else{
            
           try {
               String username = emailTextField.getText().trim(); 
               String password =paswordbre.getText();
               
               Perdoruesi p = pr.findByUsernameAndPassword(username, password);
               
               if(p != null){
                   if(p.getRoliID().getRoliID() == 1 || p.getRoliID().getRoliID() == 2){
                       //   testMain t = new testMain();
                       Dashboard d = new Dashboard(p);
                       this.dispose();
                       //t.setVisible(true);
                       //t.getButton().setEnabled(false);
                       d.setVisible(true);
                    
                   }
               }
                       
                       
                   } catch (PerdoruesiException ex) {
                           // Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                           FrameShakingEffect.vibrate(this);
                           PerdoruesiNotFound perdoruesiNotFound = new PerdoruesiNotFound(this,true);
                           perdoruesiNotFound.setVisible(true);
                           
                           
                           }
               }
       
    }//GEN-LAST:event_SignInButtonMouseClicked

    
    
            
    private void paswordbreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paswordbreActionPerformed
        
    }//GEN-LAST:event_paswordbreActionPerformed

    private void SignUpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpButtonMouseClicked
        this.dispose();
        SignupForm f = new SignupForm();
        f.setVisible(true);
    }//GEN-LAST:event_SignUpButtonMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        HelpFrame h = new HelpFrame();
        h.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      for(double i = 0.0; i<1.0;i=i+ 0.1){
          String value = i+ "";
          float f = Float.valueOf(value);
          this.setOpacity(f);
          try{
              Thread.sleep(50);
          }catch(Exception e){
              e.printStackTrace();
          }
      }
        
    }//GEN-LAST:event_formWindowOpened

    private void loginPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_loginPanelKeyTyped
            //nothing
    }//GEN-LAST:event_loginPanelKeyTyped

    private void paswordbreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paswordbreKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER){
         if(emailTextField.getText().trim().length() == 0 || paswordbre.getText().length() == 0){
           FrameShakingEffect.vibrate(this);
          AuthentitacionError a = new AuthentitacionError(this, true);
           a.setVisible(true);
            
       }else{
       try {
               String username = emailTextField.getText().trim();
               String password =paswordbre.getText();
               
               Perdoruesi p = pr.findByUsernameAndPassword(username, password);
               
               if(p != null){
                   if(p.getRoliID().getRoliID() == 1 || p.getRoliID().getRoliID() == 2){
                    
                       Dashboard d = new Dashboard(p);
                       this.dispose();
                       d.setVisible(true);
                     
                   }
               }
                       
                       
                   } catch (PerdoruesiException ex) {
                           FrameShakingEffect.vibrate(this);
                           PerdoruesiNotFound perdoruesiNotFound = new PerdoruesiNotFound(this,true);
                           perdoruesiNotFound.setVisible(true);
                           
                           
                           }
               }
       }
        
    }//GEN-LAST:event_paswordbreKeyPressed

    private void logoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoIconMouseClicked
//        try {
//            EasterEggFrame easterEggFrame = new EasterEggFrame(this,true);
//            easterEggFrame.setVisible(true);
//            URI link = new URI("https://www.youtube.com/watch?v=zSWNWWREtsI&list=RDzSWNWWREtsI&start_radio=1");
//            Desktop d = Desktop.getDesktop();
//            d.browse(link);
//        } catch (URISyntaxException ex) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (IOException ex) {
//            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_logoIconMouseClicked

 
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            this.dispose();
            ResetPasswordPanel r = new ResetPasswordPanel(emailTextField.getText());
            r.setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

        static boolean darkLightModeFlag = false;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       //light mode on :P
        
         
        if(!darkLightModeFlag){
              loginPanel.setBackground(new Color(255,255,255));
        nameFilmix.setForeground(new Color(43,43,47));
        emailTextField.setBackground(new Color(255,255,255));
         emailTextField.setForeground(new Color(43,43,47));
        emailTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(43, 43,47)));
        usernameText.setForeground(new Color(43,43,47));
        paswordbre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(43, 43,47)));
        passwordText.setForeground(new Color(43,43,47));
        paswordbre.setBackground(new Color(255,255,255));
         paswordbre.setForeground(new Color(43,43,47));
          jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_moon_symbol_30px_5.png")));
            darkLightModeFlag = true;
        }else{
           loginPanel.setBackground(new Color(47,47,43));
        nameFilmix.setForeground(new Color(255,255,255));
        emailTextField.setBackground(new Color(47,47,43));
         emailTextField.setForeground(new Color(255,255,255));
        emailTextField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255,255,255)));
        usernameText.setForeground(new Color(255,255,255));
        paswordbre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255,255)));
        passwordText.setForeground(new Color(255,255,255));
        paswordbre.setBackground(new Color(47,47,43));
         paswordbre.setForeground(new Color(255,255,255));
         jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_moon_symbol_30px_4.png")));
            darkLightModeFlag = false;
        }
      
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void emailTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailTextFieldMouseClicked
      // emailTextField.setFocusable(true);
    }//GEN-LAST:event_emailTextFieldMouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
       
        //lateeer
        
//        Component [] components = this.getContentPane().getComponents();
//        
//        for(Component component : components){
//             if(component instanceof JTextField){
//                ((JTextField)component).setForeground(new Color(43,43,47));
//                ((JTextField)component).setBackground(new Color(255,255,255));
//                ((JTextField)component).setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(43, 43,47)));
//           }
//            if(component instanceof JPanel){
//                  ((JPanel)component).setBackground(new Color(255,255,255));
//            }
//              
//            if(component instanceof JLabel){
//               ((JLabel)component).setForeground(new Color(43,43,47));
//                jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotot/icons8_moon_symbol_30px_5.png")));
//           }
//         
//           
//        }
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
       this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jLabel4MouseClicked

    static int xx,yy;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SignInButton;
    private javax.swing.JLabel SignUpButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoIcon;
    private javax.swing.JLabel nameFilmix;
    private javax.swing.JLabel notHiddenIcon;
    private javax.swing.JLabel passwordText;
    private javax.swing.JPasswordField paswordbre;
    private javax.swing.JLabel popCornGif;
    private javax.swing.JLabel usernameText;
    // End of variables declaration//GEN-END:variables
}